name: deploy

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.WEB_DISPATCH_TOKEN }}
          repository: xtwis/web
          event-type: docs-sync
          client-payload: |
            {"repo": "${{ github.repository }}", "sha": "${{ github.sha }}"}
